### ISSUE TITLE
Add COVID-19 sector code to IATI filters

### ISSUE THREAD

**Issue by stevieflow** [markbrough/covid19-data#2]
There is now a specific OECD DAC 5-digit sector code for COVID-19: 12264 https://codelists.codeforiati.org/Sector/#12264

The IATI guidance document does not include this, and therefore the tool does not check for instances of use of sector (either at the ``iati-activity/sector`` level or ``transaction/sector`` element)

To add this, we would need to:

- add a routine to ``run.py`` to check for this condition in the IATI data
-  if YES, then a) log it as covid-relevant (sector) and b) include it in the list of qualifying activities to be parsed

We know that this sector code is used in over 300 activities: https://d-portal.org/ctrack.html?sector_code=12264#view=main.  Whether *any* of these exist outside of the sweep that is undertaken by the conditions set out by the guidance is another question - but the use case can remain that a publisher could just apply the sector code to an activity/transaction, and not include citation of covid anywhere else within the activity....

@davidmegginson @mcarans any thoughts?

**Comment by davidmegginson** [comment]
This is a good first mod for one of us to make to the backend code.

**Comment by stevieflow** [comment]
Thanks @davidmegginson 

I think we could fold this change into other requests for @mcarans 

@mcarans we could use github issues and projects to do this?

**Comment by mcarans** [comment]
Closing as we are handling this issue elsewhere.
